---
name: evopt
version: "1.0.0"
slug: evopt
description: Optimierer für Ladevorgänge (evopt) als Home Assistant Add-on
url: https://github.com/andig/evopt
arch: 
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
init: false
image: andig/evopt:latest
ports:
  7050/tcp: 7050
ports_description:
  7050/tcp: "evopt HTTP API"
map:
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false
ingress: false
host_network: true
